/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
    public static inline var LetsGo:String = "event:/Music/LetsGo";
}

class FmodSFX {
    public static inline var MenuHover:String = "event:/SFX/Menu/MenuHover";
    public static inline var MenuSelect:String = "event:/SFX/Menu/MenuSelect";
    public static inline var Grab:String = "event:/SFX/Player/Grab";
    public static inline var Hit:String = "event:/SFX/Player/Hit";
    public static inline var Release:String = "event:/SFX/Player/Release";
}
