/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
    public static inline var IntoNothing:String = "event:/Music/IntoNothing";
    public static inline var LetsGo:String = "event:/Music/LetsGo";
    public static inline var Title:String = "event:/Music/Title";
    public static inline var Weightless:String = "event:/Music/Weightless";
}

class FmodSFX {
    public static inline var ButtonClick:String = "event:/SFX/Button/ButtonClick";
    public static inline var AmibenceCutsceneShip:String = "event:/SFX/Cutscene/AmibenceCutsceneShip";
    public static inline var BallBeep:String = "event:/SFX/Cutscene/BallBeep";
    public static inline var Bang:String = "event:/SFX/Cutscene/Bang";
    public static inline var Teleport:String = "event:/SFX/Cutscene/Teleport";
    public static inline var HandleComplete:String = "event:/SFX/Handle/HandleComplete";
    public static inline var HandleLock:String = "event:/SFX/Handle/HandleLock";
    public static inline var Squeak:String = "event:/SFX/Handle/Squeak";
    public static inline var MenuHover:String = "event:/SFX/Menu/MenuHover";
    public static inline var MenuSelect:String = "event:/SFX/Menu/MenuSelect";
    public static inline var Ship:String = "event:/SFX/OpeningScene/Ship";
    public static inline var Grab:String = "event:/SFX/Player/Grab";
    public static inline var Hit:String = "event:/SFX/Player/Hit";
    public static inline var Release:String = "event:/SFX/Player/Release";
}
